### ISSUE TITLE
Channel errorstate cache not found   

### ISSUE THREAD

**Issue by ItJustFox** [parkervcp/parkertron#52] opened 2023-06-06 03:43 UTC
Hello there, I got this error

```[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./parkertron
2023/06/06 05:40:19 starting logging
INFO[0000] logging online                               
INFO[0000] channel groups [947240213661503548 947242656210223124 1039878243735572510] 
INFO[0000] 
                      __             __
    ____  ____ ______/ /_____  _____/ /__________  ____
   / __ \/ __ '/ ___/ //_/ _ \/ ___/ __/ ___/ __ \/ __ \
  / /_/ / /_/ / /  / ,< /  __/ /  / /_/ /  / /_/ / / / /
 / .___/\__,_/_/  /_/|_|\___/_/   \__/_/   \____/_/ /_/
/_/ v.0.3.1
 
INFO[0000] Starting discord server connections          
INFO[0000] Connecting to FantucieSupportServer          
INFO[0000] Bot is now running. Send 'shutdown' or 'ctrl + c' to stop the bot. 
Jexactyl: Server marked as running...
FATA[0062] Channel errorstate cache not found           
Jexactyl: Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
```

Just after dm's the bot on discord to try the answer ?

**Comment by parkervcp** [comment] 2023-06-06 22:02
duplicate of #50

**Closed as completed by parkervcp** 2023-06-06 22:02 UTC
